//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string AccessType {
            get {
                return ResourceManager.GetString("AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دسترسی.
        /// </summary>
        public static string AccessType1 {
            get {
                return ResourceManager.GetString("AccessType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزاد.
        /// </summary>
        public static string AccessTypePublic {
            get {
                return ResourceManager.GetString("AccessTypePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد از ورود.
        /// </summary>
        public static string AccessTypeRegistered {
            get {
                return ResourceManager.GetString("AccessTypeRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژه.
        /// </summary>
        public static string AccessTypeSpecial {
            get {
                return ResourceManager.GetString("AccessTypeSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال‌سازی خودکار کاربر بعد از ثبت‌نام.
        /// </summary>
        public static string ActivateUserAfterRegistration {
            get {
                return ResourceManager.GetString("ActivateUserAfterRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مدیریتی.
        /// </summary>
        public static string AdminDescription {
            get {
                return ResourceManager.GetString("AdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت سامانه.
        /// </summary>
        public static string ApplicationHandler {
            get {
                return ResourceManager.GetString("ApplicationHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت موجودیت های سامانه.
        /// </summary>
        public static string ApplicationHandlerManager {
            get {
                return ResourceManager.GetString("ApplicationHandlerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت های سامانه.
        /// </summary>
        public static string ApplicationHandlers {
            get {
                return ResourceManager.GetString("ApplicationHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سامانه.
        /// </summary>
        public static string ApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صعودی.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل.
        /// </summary>
        public static string AuthenticationTypeGoogle {
            get {
                return ResourceManager.GetString("AuthenticationTypeGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داخلی.
        /// </summary>
        public static string AuthenticationTypeInternal {
            get {
                return ResourceManager.GetString("AuthenticationTypeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BaseTable {
            get {
                return ResourceManager.GetString("BaseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BaseTableEnum {
            get {
                return ResourceManager.GetString("BaseTableEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم اطلاعات پایه.
        /// </summary>
        public static string BaseTableItem {
            get {
                return ResourceManager.GetString("BaseTableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم‌های اطلاعات پایه.
        /// </summary>
        public static string BaseTableItems {
            get {
                return ResourceManager.GetString("BaseTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم‌های اطلاعات پایه.
        /// </summary>
        public static string BaseTableItemsOf {
            get {
                return ResourceManager.GetString("BaseTableItemsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BaseTables {
            get {
                return ResourceManager.GetString("BaseTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اطلاعات پایه.
        /// </summary>
        public static string BaseTableType {
            get {
                return ResourceManager.GetString("BaseTableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اطلاعات پایه.
        /// </summary>
        public static string BaseTableTypeEnum {
            get {
                return ResourceManager.GetString("BaseTableTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبلاگ.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن اصلی.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایین.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه‌بندی‌ها.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه‌بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string CellPhoneNumberInBrief {
            get {
                return ResourceManager.GetString("CellPhoneNumberInBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumberVerificationKey {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انقضا کد تایید شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumberVerificationKeyExpireDateTime {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKeyExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فرزندان.
        /// </summary>
        public static string ChildCount {
            get {
                return ResourceManager.GetString("ChildCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرزندان.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه بندی.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت محتوا.
        /// </summary>
        public static string CmsSettings {
            get {
                return ResourceManager.GetString("CmsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات.
        /// </summary>
        public static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کامنت‌ها.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات عمومی.
        /// </summary>
        public static string CommonSettings {
            get {
                return ResourceManager.GetString("CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه جدید.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی‌رایت.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی تصویر کاور.
        /// </summary>
        public static string CoverImageUrl {
            get {
                return ResourceManager.GetString("CoverImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string CreateOf {
            get {
                return ResourceManager.GetString("CreateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد اطلاعات تستی.
        /// </summary>
        public static string CreateTestData {
            get {
                return ResourceManager.GetString("CreateTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ایجاد کننده.
        /// </summary>
        public static string CreatorUser {
            get {
                return ResourceManager.GetString("CreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ایجاد کننده.
        /// </summary>
        public static string CreatorUserId {
            get {
                return ResourceManager.GetString("CreatorUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان‌ها.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string CultureTemp {
            get {
                return ResourceManager.GetString("CultureTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جاری.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string Deactive {
            get {
                return ResourceManager.GetString("Deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان پیش‌فرض.
        /// </summary>
        public static string DefaultCulture {
            get {
                return ResourceManager.GetString("DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [مقدار ندارد].
        /// </summary>
        public static string DefaultNullValue {
            get {
                return ResourceManager.GetString("DefaultNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان حذف.
        /// </summary>
        public static string DeleteDateTime {
            get {
                return ResourceManager.GetString("DeleteDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string DeleteOf {
            get {
                return ResourceManager.GetString("DeleteOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات تستی.
        /// </summary>
        public static string DeleteTestData {
            get {
                return ResourceManager.GetString("DeleteTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نزولی.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string DetailsOf {
            get {
                return ResourceManager.GetString("DetailsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ارقام در کد امنیتی.
        /// </summary>
        public static string DigitCountInCaptchaImage {
            get {
                return ResourceManager.GetString("DigitCountInCaptchaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کامنت‌ها بعد از تایید.
        /// </summary>
        public static string DisplayCommentsAfterVerification {
            get {
                return ResourceManager.GetString("DisplayCommentsAfterVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کاربر خالق.
        /// </summary>
        public static string DisplayCreatorUser {
            get {
                return ResourceManager.GetString("DisplayCreatorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در صفحه تماس با ما.
        /// </summary>
        public static string DisplayInContactUsPage {
            get {
                return ResourceManager.GetString("DisplayInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در خانه.
        /// </summary>
        public static string DisplayInHomePage {
            get {
                return ResourceManager.GetString("DisplayInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایش داده شده، در صفحه تماس با ما.
        /// </summary>
        public static string DisplayNameInContactUsPage {
            get {
                return ResourceManager.GetString("DisplayNameInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش مشخصات.
        /// </summary>
        public static string DisplayProfile {
            get {
                return ResourceManager.GetString("DisplayProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موتورهای جستجو لینک‌های داخل صفحه را دنبال می‌کنند.
        /// </summary>
        public static string DoesSearchEnginesFollowIt {
            get {
                return ResourceManager.GetString("DoesSearchEnginesFollowIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موتورهای جستجو محتوای صفحه را بررسی می‌کنند.
        /// </summary>
        public static string DoesSearchEnginesIndexIt {
            get {
                return ResourceManager.GetString("DoesSearchEnginesIndexIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دانلود.
        /// </summary>
        public static string DownloadCount {
            get {
                return ResourceManager.GetString("DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست‌الکترونیکی.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string EmailAddressInBrief {
            get {
                return ResourceManager.GetString("EmailAddressInBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید نشانی پست‌الکترونیکی.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن نامه.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع نامه.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح مورد نظر برای پروفایل کاربر.
        /// </summary>
        public static string FavoriteUserProfileLevel {
            get {
                return ResourceManager.GetString("FavoriteUserProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پوشه‌ها و فایل‌ها.
        /// </summary>
        public static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت‌ها.
        /// </summary>
        public static string Genders {
            get {
                return ResourceManager.GetString("Genders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گوگل.
        /// </summary>
        public static string GoogleCode {
            get {
                return ResourceManager.GetString("GoogleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست داشتن.
        /// </summary>
        public static string HasAttachment {
            get {
                return ResourceManager.GetString("HasAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        public static string Hits {
            get {
                return ResourceManager.GetString("Hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات HTML.
        /// </summary>
        public static string HtmlSetting {
            get {
                return ResourceManager.GetString("HtmlSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت آیکون.
        /// </summary>
        public static string IconPosition {
            get {
                return ResourceManager.GetString("IconPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string IdentityAdminSettings {
            get {
                return ResourceManager.GetString("IdentityAdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کاربری.
        /// </summary>
        public static string IdentitySettings {
            get {
                return ResourceManager.GetString("IdentitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی تصویر.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد.
        /// </summary>
        public static string InsertDateTime {
            get {
                return ResourceManager.GetString("InsertDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاصله زمانی.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدمه.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی‌پی.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال‌سازی کد امنیتی.
        /// </summary>
        public static string IsCaptchaImageEnabled {
            get {
                return ResourceManager.GetString("IsCaptchaImageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه تایید شده است.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان نظردهی.
        /// </summary>
        public static string IsCommentingEnabled {
            get {
                return ResourceManager.GetString("IsCommentingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تماس با ما.
        /// </summary>
        public static string IsContactUsEnabled {
            get {
                return ResourceManager.GetString("IsContactUsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد پیش فرض.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string IsDeletedInBrief {
            get {
                return ResourceManager.GetString("IsDeletedInBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string IsDisabled {
            get {
                return ResourceManager.GetString("IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش‌نویس.
        /// </summary>
        public static string IsDraft {
            get {
                return ResourceManager.GetString("IsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی تایید شده است.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژه.
        /// </summary>
        public static string IsFeatured {
            get {
                return ResourceManager.GetString("IsFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ورود به سامانه از طریق گوگل.
        /// </summary>
        public static string IsGoogleAuthenticationEnabled {
            get {
                return ResourceManager.GetString("IsGoogleAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش ورود به سامانه.
        /// </summary>
        public static string IsLoginVisible {
            get {
                return ResourceManager.GetString("IsLoginVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تایید شده.
        /// </summary>
        public static string IsNationalCodeVerified {
            get {
                return ResourceManager.GetString("IsNationalCodeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل عمومی است.
        /// </summary>
        public static string IsProfilePublic {
            get {
                return ResourceManager.GetString("IsProfilePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه‌نویس.
        /// </summary>
        public static string IsProgrammer {
            get {
                return ResourceManager.GetString("IsProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت‌نام.
        /// </summary>
        public static string IsRegistrationEnabled {
            get {
                return ResourceManager.GetString("IsRegistrationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان جستجوی مطالب در منوی سایت.
        /// </summary>
        public static string IsSearchInNavbarEnabled {
            get {
                return ResourceManager.GetString("IsSearchInNavbarEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همگام‌سازی شده.
        /// </summary>
        public static string IsSynced {
            get {
                return ResourceManager.GetString("IsSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستمی.
        /// </summary>
        public static string IsSystemic {
            get {
                return ResourceManager.GetString("IsSystemic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تستی.
        /// </summary>
        public static string IsTestData {
            get {
                return ResourceManager.GetString("IsTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر قابل حذف.
        /// </summary>
        public static string IsUndeletable {
            get {
                return ResourceManager.GetString("IsUndeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل ویرایش.
        /// </summary>
        public static string IsUpdatable {
            get {
                return ResourceManager.GetString("IsUpdatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        public static string IsVerified {
            get {
                return ResourceManager.GetString("IsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string IsVerifiedInBrief {
            get {
                return ResourceManager.GetString("IsVerifiedInBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل مشاهده.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در صفحه تماس با ما.
        /// </summary>
        public static string IsVisibleInContactUsPage {
            get {
                return ResourceManager.GetString("IsVisibleInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد آیتم‌ها.
        /// </summary>
        public static string ItemCount {
            get {
                return ResourceManager.GetString("ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم‌ها.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم‌های.
        /// </summary>
        public static string ItemsOf {
            get {
                return ResourceManager.GetString("ItemsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کلیدی.
        /// </summary>
        public static string KeyName {
            get {
                return ResourceManager.GetString("KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیدواژه ها.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان‌ها.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آخرین تغییر گذرواژه.
        /// </summary>
        public static string LastChangePasswordDateTime {
            get {
                return ResourceManager.GetString("LastChangePasswordDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مدرک تحصیلی.
        /// </summary>
        public static string LastEducationDegree {
            get {
                return ResourceManager.GetString("LastEducationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین مدرک تحصیلی.
        /// </summary>
        public static string LastGrade {
            get {
                return ResourceManager.GetString("LastGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آخرین ورود.
        /// </summary>
        public static string LastLoginDateTime {
            get {
                return ResourceManager.GetString("LastLoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب صفحه.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب دلخواه.
        /// </summary>
        public static string LayoutCustom {
            get {
                return ResourceManager.GetString("LayoutCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب پیش‌فرض.
        /// </summary>
        public static string LayoutDefault {
            get {
                return ResourceManager.GetString("LayoutDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب خالی.
        /// </summary>
        public static string LayoutEmpty {
            get {
                return ResourceManager.GetString("LayoutEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب‌های صفحات.
        /// </summary>
        public static string Layouts {
            get {
                return ResourceManager.GetString("Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصه زبان.
        /// </summary>
        public static string Lcid {
            get {
                return ResourceManager.GetString("Lcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چپ.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست.
        /// </summary>
        public static string ListOf {
            get {
                return ResourceManager.GetString("ListOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست {0}.
        /// </summary>
        public static string ListOfItems {
            get {
                return ResourceManager.GetString("ListOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سامانه برحسب زبان.
        /// </summary>
        public static string LocalizedApplicationSetting {
            get {
                return ResourceManager.GetString("LocalizedApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات صفحه اول سامانه برحسب زبان.
        /// </summary>
        public static string LocalizedHomePageSetting {
            get {
                return ResourceManager.GetString("LocalizedHomePageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ایمیل و Mail Server برحسب زبان.
        /// </summary>
        public static string LocalizedMailSetting {
            get {
                return ResourceManager.GetString("LocalizedMailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ورود به سامانه.
        /// </summary>
        public static string LoginDateTime {
            get {
                return ResourceManager.GetString("LoginDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودهای به سامانه.
        /// </summary>
        public static string LoginLogs {
            get {
                return ResourceManager.GetString("LoginLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه ورود به سامانه.
        /// </summary>
        public static string LoginOption {
            get {
                return ResourceManager.GetString("LoginOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ورود.
        /// </summary>
        public static string LoginType {
            get {
                return ResourceManager.GetString("LoginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خروج از سامانه.
        /// </summary>
        public static string LogoutDateTime {
            get {
                return ResourceManager.GetString("LogoutDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string ManageOf {
            get {
                return ResourceManager.GetString("ManageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تاهل.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه اصلی (شاه کلید).
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد مطالب.
        /// </summary>
        public static string MaxDisplayPostCount {
            get {
                return ResourceManager.GetString("MaxDisplayPostCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد مطالب در صفحه خانه.
        /// </summary>
        public static string MaxPostCountInHomePage {
            get {
                return ResourceManager.GetString("MaxPostCountInHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد مطالب در صفحه اصلی.
        /// </summary>
        public static string MaxPostCountInMainPage {
            get {
                return ResourceManager.GetString("MaxPostCountInMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد مطالب در صفحه پروفایل.
        /// </summary>
        public static string MaxPostCountInProfilePage {
            get {
                return ResourceManager.GetString("MaxPostCountInProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم منو.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم‌های منو.
        /// </summary>
        public static string MenuItems {
            get {
                return ResourceManager.GetString("MenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نظام وظیفه.
        /// </summary>
        public static string MilitaryServiceStatus {
            get {
                return ResourceManager.GetString("MilitaryServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت نظام‌وظیفه.
        /// </summary>
        public static string MilitaryStatus {
            get {
                return ResourceManager.GetString("MilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی فیلم.
        /// </summary>
        public static string MovieUrl {
            get {
                return ResourceManager.GetString("MovieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بومی.
        /// </summary>
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک.
        /// </summary>
        public static string NavigationUrl {
            get {
                return ResourceManager.GetString("NavigationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون والد.
        /// </summary>
        public static string NoParent {
            get {
                return ResourceManager.GetString("NoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نشده.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید نشده.
        /// </summary>
        public static string NotVerified {
            get {
                return ResourceManager.GetString("NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاربران دارای این نقش.
        /// </summary>
        public static string NumberOfUsersWithThisRole {
            get {
                return ResourceManager.GetString("NumberOfUsersWithThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صفحه جدید باز شود.
        /// </summary>
        public static string OpenUrlInNewWindow {
            get {
                return ResourceManager.GetString("OpenUrlInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب‌سازی بر اساس.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیدمان.
        /// </summary>
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالک.
        /// </summary>
        public static string OwnerUser {
            get {
                return ResourceManager.GetString("OwnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد صفحات.
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره صفحه.
        /// </summary>
        public static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اطلاعات در هر صفحه.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والد.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوزها.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پوشه‌ها و فایل‌های شخصی.
        /// </summary>
        public static string PersonalFileManager {
            get {
                return ResourceManager.GetString("PersonalFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فردی.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلب.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه‌بندی‌های مطالب.
        /// </summary>
        public static string PostCategories {
            get {
                return ResourceManager.GetString("PostCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه‌بندی مطلب.
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مطالب.
        /// </summary>
        public static string PostCount {
            get {
                return ResourceManager.GetString("PostCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطالب.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی مطالب.
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی‌های مطالب.
        /// </summary>
        public static string PostTypes {
            get {
                return ResourceManager.GetString("PostTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشوند.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش‌نمایش.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح پروفایل کاربر.
        /// </summary>
        public static string ProfileLevel {
            get {
                return ResourceManager.GetString("ProfileLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و زمان پایان انتشار.
        /// </summary>
        public static string PublishFinishDateTime {
            get {
                return ResourceManager.GetString("PublishFinishDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و زمان شروع انتشار.
        /// </summary>
        public static string PublishStartDateTime {
            get {
                return ResourceManager.GetString("PublishStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرنده.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی گیرنده.
        /// </summary>
        public static string RecipientDisplayName {
            get {
                return ResourceManager.GetString("RecipientDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی گیرنده.
        /// </summary>
        public static string RecipientEmailAddress {
            get {
                return ResourceManager.GetString("RecipientEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اطلاعات.
        /// </summary>
        public static string RecordCount {
            get {
                return ResourceManager.GetString("RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت‌نام.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیازمند ورود به سامانه.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی‌پی کاربر در زمان ثبت‌نام.
        /// </summary>
        public static string RegisterIP {
            get {
                return ResourceManager.GetString("RegisterIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ثبت‌نام.
        /// </summary>
        public static string RegisterTime {
            get {
                return ResourceManager.GetString("RegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ثبت‌نام.
        /// </summary>
        public static string RegisterType {
            get {
                return ResourceManager.GetString("RegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذهب.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا به خاطر داشته باش.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر حذف کننده.
        /// </summary>
        public static string RemoverUser {
            get {
                return ResourceManager.GetString("RemoverUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر حذف کننده.
        /// </summary>
        public static string RemoverUserId {
            get {
                return ResourceManager.GetString("RemoverUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزومه.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راست.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش فعال است.
        /// </summary>
        public static string RoleIsActive {
            get {
                return ResourceManager.GetString("RoleIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نقش ها.
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string RowNumber {
            get {
                return ResourceManager.GetString("RowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیازات.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانیه.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزینه‌ای را انتخاب نمایید.
        /// </summary>
        public static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داریوش تصدیقی.
        /// </summary>
        public static string SiteAuthor {
            get {
                return ResourceManager.GetString("SiteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت‌ها.
        /// </summary>
        public static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت‌ها.
        /// </summary>
        public static string Sites1 {
            get {
                return ResourceManager.GetString("Sites1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی سایت.
        /// </summary>
        public static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسلاید.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسلایدها.
        /// </summary>
        public static string Slides {
            get {
                return ResourceManager.GetString("Slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه‌های اجتماعی.
        /// </summary>
        public static string SocialNetworks {
            get {
                return ResourceManager.GetString("SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سورس‌کد.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاص.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه‌بندی‌های مطالب.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیر منوها.
        /// </summary>
        public static string SubMenuItems {
            get {
                return ResourceManager.GetString("SubMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تست.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تست.
        /// </summary>
        public static string TestOf {
            get {
                return ResourceManager.GetString("TestOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم سایت.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریک.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روشن.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از هر دو طریق.
        /// </summary>
        public static string ThroughBoth {
            get {
                return ResourceManager.GetString("ThroughBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط از طریق نشانی پست الکترونیک.
        /// </summary>
        public static string ThroughEmailAddress {
            get {
                return ResourceManager.GetString("ThroughEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط از طریق شناسه‌کاربری.
        /// </summary>
        public static string ThroughUsername {
            get {
                return ResourceManager.GetString("ThroughUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد زمانی.
        /// </summary>
        public static string TimeUnit {
            get {
                return ResourceManager.GetString("TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان کاربر در صفحه تماس با ما.
        /// </summary>
        public static string TitleInContactUsPage {
            get {
                return ResourceManager.GetString("TitleInContactUsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالا.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی‌ها.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ویرایش.
        /// </summary>
        public static string UpdateDateTime {
            get {
                return ResourceManager.GetString("UpdateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string UpdateOf {
            get {
                return ResourceManager.GetString("UpdateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصات.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش اطلاعات.
        /// </summary>
        public static string UpdateProfileDate {
            get {
                return ResourceManager.GetString("UpdateProfileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ویرایش پروفایل.
        /// </summary>
        public static string UpdateProfileTime {
            get {
                return ResourceManager.GetString("UpdateProfileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر ویرایش کننده.
        /// </summary>
        public static string UpdaterUserId {
            get {
                return ResourceManager.GetString("UpdaterUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاربران.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری / نشانی پست الکترونیکی.
        /// </summary>
        public static string UsernameOrEmailAddress {
            get {
                return ResourceManager.GetString("UsernameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری / شماره تلفن هراه حساب.
        /// </summary>
        public static string UsernameOrPhoneNumber {
            get {
                return ResourceManager.GetString("UsernameOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربر در سامانه.
        /// </summary>
        public static string UserRoleTitle {
            get {
                return ResourceManager.GetString("UserRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت‌های کاربر.
        /// </summary>
        public static string UserSites {
            get {
                return ResourceManager.GetString("UserSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انقضا کد تایید پست الکترونیکی.
        /// </summary>
        public static string VerificationKeyExpireDateTime {
            get {
                return ResourceManager.GetString("VerificationKeyExpireDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تایید.
        /// </summary>
        public static string VerifyDateTime {
            get {
                return ResourceManager.GetString("VerifyDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب‌سایت‌ها.
        /// </summary>
        public static string Websites {
            get {
                return ResourceManager.GetString("Websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفته.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون نقش.
        /// </summary>
        public static string WithoutRole {
            get {
                return ResourceManager.GetString("WithoutRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلی.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
