//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه شما دسترسی کافی برای مشاهده این صفحه را ندارید!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است! لطفا از {0} دیگری استفاده نمایید..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما باید فیلد کد امنیتی را با دقت و با ارقام انگلیسی تکمیل نمایید!.
        /// </summary>
        public static string CaptchaImage {
            get {
                return ResourceManager.GetString("CaptchaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی را به درستی وارد نکرده‌اید!.
        /// </summary>
        public static string CaptchaImageIsNotCorrect {
            get {
                return ResourceManager.GetString("CaptchaImageIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از این {0} در جای دیگری استفاده شده است، لذا شما قادر به حذف آن نمی‌باشید!.
        /// </summary>
        public static string CascadeDelete {
            get {
                return ResourceManager.GetString("CascadeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این آیتم اطمینان دارید؟.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جاری صحیح نمی‌باشد!.
        /// </summary>
        public static string CurrentPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست‌الکترونیکی و/یا گذرواژه صحیح نمی‌باشد!.
        /// </summary>
        public static string EmailAddressAndOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("EmailAddressAndOrPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی شما هنوز تایید نشده است!.
        /// </summary>
        public static string EmailAddressIsNotVerified {
            get {
                return ResourceManager.GetString("EmailAddressIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اطلاعات باید مشخص شده باشد!.
        /// </summary>
        public static string IdIsNull {
            get {
                return ResourceManager.GetString("IdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اعتبارسنجی اشتباه است. لطفا با دقت بیشتری کد را وارد کنید..
        /// </summary>
        public static string InvalidOtpCode {
            get {
                return ResourceManager.GetString("InvalidOtpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری و یا گذرواژه صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعاتی یافت نشد!.
        /// </summary>
        public static string ItemsNotFound {
            get {
                return ResourceManager.GetString("ItemsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جدید نمی‌تواند با گذرواژه جاری یکسان باشد!.
        /// </summary>
        public static string NewPasswordCanNotBeSameAsCurrentPassword {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeSameAsCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر یافت نشد!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبابل تایید نشده است..
        /// </summary>
        public static string PhoneNumberIsNotVerified {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت‌نام در حال حاضر وجود ندارد!.
        /// </summary>
        public static string RegistrationIsNotActiveRightNow {
            get {
                return ResourceManager.GetString("RegistrationIsNotActiveRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعاتی با چنین شناسه‌ای وجود ندارد!.
        /// </summary>
        public static string ThereIsNotAnyDataWithThisId {
            get {
                return ResourceManager.GetString("ThereIsNotAnyDataWithThisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سامانه، هیچ کاربری با چنین شناسه‌کاربری یا نشانی پست الکترونیکی وجود ندارد!.
        /// </summary>
        public static string ThereIsNotAnyUserWithThisUsernameOrEmailAddress {
            get {
                return ResourceManager.GetString("ThereIsNotAnyUserWithThisUsernameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سامانه، هیچ کاربری با چنین شناسه‌کاربری یا شماره تلفن همراهی وجود ندارد!.
        /// </summary>
        public static string ThereIsNotAnyUserWithThisUsernameOrPhoneNumber {
            get {
                return ResourceManager.GetString("ThereIsNotAnyUserWithThisUsernameOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان {0} این {1} وجود ندارد!.
        /// </summary>
        public static string UnableTo {
            get {
                return ResourceManager.GetString("UnableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تعریف والد برای این آیتم، به علت وجود زیر مجموعه وجود ندارد!.
        /// </summary>
        public static string UnableToUpdateParent {
            get {
                return ResourceManager.GetString("UnableToUpdateParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته‌ای صورت گرفته است! لطفا با تیم پشتیبانی تماس حاصل فرمایید..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما به سامانه تا اطلاع ثانوی مسدود می‌باشد!.
        /// </summary>
        public static string UserAccountIsNotActive {
            get {
                return ResourceManager.GetString("UserAccountIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه تا اطلاع ثانوی، امکان ورود به سامانه، برای شما مقدور نمی‌باشد!.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری و/یا نشانی پست‌الکترونیکی و/یا گذرواژه صحیح نمی‌باشد!.
        /// </summary>
        public static string UsernameAndOrEmailAddressAndOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("UsernameAndOrEmailAddressAndOrPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری و/یا گذرواژه صحیح نمی‌باشد!.
        /// </summary>
        public static string UsernameAndOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("UsernameAndOrPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌کاربری و/یا شماره همراه و/یا گذرواژه صحیح نمی‌باشد!.
        /// </summary>
        public static string UsernameAndOrPhoneNumberAndOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("UsernameAndOrPhoneNumberAndOrPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه تا اطلاع ثانوی، امکان ورود به سامانه، برای شما (با توجه به نقشی که در سامانه به شما تخصیص داده شده است) مقدور نمی‌باشد!.
        /// </summary>
        public static string YourRoleIsNotActive {
            get {
                return ResourceManager.GetString("YourRoleIsNotActive", resourceCulture);
            }
        }
    }
}
