//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Successes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Successes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Successes", typeof(Successes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب شما با موفقیت فعال شد اکنون میتوانید وارد شوید..
        /// </summary>
        public static string AccountVerified {
            get {
                return ResourceManager.GetString("AccountVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به درخواست شما، یک ایمیل برای صندوق پست الکترونیکی‌تان ارسال گردید، لطفا آن‌را چک نمایید..
        /// </summary>
        public static string CheckYourMailbox {
            get {
                return ResourceManager.GetString("CheckYourMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به درخواست شما، یک اس ام اس برای شماره تلفن همراه‌تان ارسال گردید، لطفا آن‌را چک نمایید..
        /// </summary>
        public static string CheckYourSMSbox {
            get {
                return ResourceManager.GetString("CheckYourSMSbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت ایجاد گردید..
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت حذف گردید..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل با موفقیت ارسال گردید..
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه شما با موفقیت تغییر پیدا کرد..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تکمیل ثبت نام کد ارسال شده را وارد کنید..
        /// </summary>
        public static string RegistrationDone {
            get {
                return ResourceManager.GetString("RegistrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت ویرایش گردید..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شما با موفقیت ذخیره گردید..
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} کاربر حذف گردید..
        /// </summary>
        public static string UserCountDeleted {
            get {
                return ResourceManager.GetString("UserCountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب شما قبلا تایید شده است..
        /// </summary>
        public static string YourCellPhoneNumberHasBeenAlreadyVerified {
            get {
                return ResourceManager.GetString("YourCellPhoneNumberHasBeenAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی شما قبلا تایید شده است..
        /// </summary>
        public static string YourEmailAddressHasBeenAlreadyVerified {
            get {
                return ResourceManager.GetString("YourEmailAddressHasBeenAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی شما تایید گردید..
        /// </summary>
        public static string YourEmailAddressVerified {
            get {
                return ResourceManager.GetString("YourEmailAddressVerified", resourceCulture);
            }
        }
    }
}
