// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.SqlServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Features.Common.BaseTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsertDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("bit");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BaseTables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c558b71f-dca1-477b-9728-58f3e5081fc1"),
                            Code = 1100,
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(1896), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsSynced = false,
                            IsTestData = false,
                            Ordering = 10000,
                            Type = 0,
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(1896), new TimeSpan(0, 3, 30, 0, 0))
                        });
                });

            modelBuilder.Entity("Domain.Features.Common.BaseTableItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("InsertDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("bit");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BaseTableId");

                    b.ToTable("BaseTableItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29d863fe-8504-4a9e-8cd2-8efc2bfaaee2"),
                            BaseTableId = new Guid("c558b71f-dca1-477b-9728-58f3e5081fc1"),
                            Code = 0,
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2146), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsSynced = false,
                            IsTestData = false,
                            KeyName = "SimpleUser",
                            Ordering = 1000,
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2146), new TimeSpan(0, 3, 30, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("c2539a70-ad1c-4c89-8bea-eaeb81615ff9"),
                            BaseTableId = new Guid("c558b71f-dca1-477b-9728-58f3e5081fc1"),
                            Code = 300,
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2216), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsSynced = false,
                            IsTestData = false,
                            KeyName = "Administrator",
                            Ordering = 4000,
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2216), new TimeSpan(0, 3, 30, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("210262a3-b878-4fea-ae21-1cd3be57d355"),
                            BaseTableId = new Guid("c558b71f-dca1-477b-9728-58f3e5081fc1"),
                            Code = 400,
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2259), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsSynced = false,
                            IsTestData = false,
                            KeyName = "ApplicationOwner",
                            Ordering = 5000,
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2259), new TimeSpan(0, 3, 30, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("b7bb7615-1d74-452c-a3a0-e85076b04c20"),
                            BaseTableId = new Guid("c558b71f-dca1-477b-9728-58f3e5081fc1"),
                            Code = 900,
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2364), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsSynced = false,
                            IsTestData = false,
                            KeyName = "Programmer",
                            Ordering = 6000,
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2364), new TimeSpan(0, 3, 30, 0, 0))
                        });
                });

            modelBuilder.Entity("Domain.Features.Identity.LoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InsertDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoginType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LogoutDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserIP");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("Domain.Features.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CellPhoneNumberVerificationKey")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTimeOffset>("InsertDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCellPhoneNumberVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUndeletable")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastChangePasswordDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastLoginDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(44)
                        .IsUnicode(false)
                        .HasColumnType("varchar(44)");

                    b.Property<string>("RegisterIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SecurityKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdateDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CellPhoneNumber")
                        .IsUnique();

                    b.HasIndex("NationalCode")
                        .IsUnique()
                        .HasFilter("[NationalCode] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2e07f37-f8c7-4328-87ab-85ee4bf61dde"),
                            CellPhoneNumber = "+989903333615",
                            InsertDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2410), new TimeSpan(0, 3, 30, 0, 0)),
                            IsActive = true,
                            IsCellPhoneNumberVerified = true,
                            IsUndeletable = true,
                            LastChangePasswordDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(3111), new TimeSpan(0, 3, 30, 0, 0)),
                            Ordering = 1000,
                            Password = "yiWZY9ZeObt6nMoNLcILU33J0TGH5kO613g+cwKtqFU=",
                            RegisterIP = "::1",
                            RoleId = new Guid("b7bb7615-1d74-452c-a3a0-e85076b04c20"),
                            SecurityKey = new Guid("00000000-0000-0000-0000-000000000000"),
                            UpdateDateTime = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 55, 51, 246, DateTimeKind.Unspecified).AddTicks(2410), new TimeSpan(0, 3, 30, 0, 0)),
                            Username = "Amirreza"
                        });
                });

            modelBuilder.Entity("Domain.Features.Common.BaseTableItem", b =>
                {
                    b.HasOne("Domain.Features.Common.BaseTable", "BaseTable")
                        .WithMany("BaseTableItems")
                        .HasForeignKey("BaseTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTable");
                });

            modelBuilder.Entity("Domain.Features.Identity.LoginLog", b =>
                {
                    b.HasOne("Domain.Features.Identity.User", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Features.Identity.User", b =>
                {
                    b.HasOne("Domain.Features.Common.BaseTableItem", "Role")
                        .WithMany("Users_Role")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Features.Common.BaseTable", b =>
                {
                    b.Navigation("BaseTableItems");
                });

            modelBuilder.Entity("Domain.Features.Common.BaseTableItem", b =>
                {
                    b.Navigation("Users_Role");
                });

            modelBuilder.Entity("Domain.Features.Identity.User", b =>
                {
                    b.Navigation("LoginLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
